name: Test
on: [push]
defaults:
  run:
    working-directory: ./
jobs:
  # rspec:
  #   runs-on: ubuntu-latest
  #   services:
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: 3.2.2
  #       bundler-cache: true
  #   - name: Run RSpec
  #     run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop --parallel
